title: Hacker-Blog
description: "A Blog for Ethical Hackers and Cyber Security Researcher"
author:
  name: "Hack Security Net"
  email: "someone@somewebsite.somedomain"
  url: "https://hacksecuritynet.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2025"
